version: "3"
services:
  couchbase:
    container_name: couchmovies_server
    image: couchmovies_server
    build: 
      context: ./couchbase
      dockerfile: Dockerfile
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
 
